---
server:
  port: 8080
  contextPath: /eshramik
---
spring:
  profiles: local
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect

---
spring.mail.host : smtp.mailhost.com
spring.mail.username : mailUser
spring.mail.password : mailPass
spring.mail.port : 587
spring.mail.properties.mail.smtp.auth : true
spring.mail.properties.mail.smtp.starttls.enable : true

